project:
  type: book
  output-dir: _site

book:
  title: Open and Reprodubile Science in R
  subtitle: Technical Handbook
  author:
    - Ernest Guevarra
    - Proochista Ariana
  date: last-modified
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - 00-introduction.qmd
    - part: Tools
      chapters:
        - 01-installing-software.qmd
        - 02-introduction-to-r.qmd
        - 03-introduction-to-git.qmd
        - 04-connecting-git-with-rstudio.qmd
    - part: Practices
      chapters:
        - 05-writing-functions.qmd
    - part: Processes
      chapters:
        - 06-clone-repository-rstudio.qmd
        - 07-commit-and-push.qmd
        - 08-participating-rstudio-project.qmd
        - 09-initiating-rstudio-project.qmd
        - 10-creating-portable-reproducible-workflows.qmd
        - 11-contributing-to-codehub-projects.qmd
  cover-image: images/ihealth_base_pos_tn.png

bibliography: references.bib

format:
  html:
    theme: cosmo
    highlight-style: breeze
  pdf:
    documentclass: scrreprt
    highlight-style: breeze
  epub:
    cover-image: images/ihealth_base_pos_tn.png
    highlight-style: breeze