project:
  type: book
  output-dir: _site

book:
  title: Open and Reprodubile Science in R
  subtitle: Technical Handbook
  author:
    - Ernest Guevarra
    - Proochista Ariana
  date: last-modified
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - introduction.qmd
    - part: Tools
      chapters:
        - installing-software.qmd
        - introduction-to-r.qmd
        - introduction-to-git.qmd
        - connecting-git-with-rstudio.qmd
    - part: Practices
      chapters:
        - writing-functions.qmd
    - part: Processes
      chapters:
        - clone-repository-rstudio.qmd
        - commit-and-push.qmd
        - participating-rstudio-project.qmd
        - initiating-rstudio-project.qmd
        - creating-portable-reproducible-workflows.qmd
        - contributing-to-codehub-projects.qmd
  cover-image: images/ihealth_base_pos_tn.png
  search: true
  repo-url: https://github.com/OxfordIHTM/ihtm-handbook/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]

bibliography: references.bib

format:
  html:
    theme: cosmo
    highlight-style: breeze
  pdf:
    documentclass: scrreprt
    highlight-style: breeze
  epub:
    cover-image: images/ihealth_base_pos_tn.png
    highlight-style: breeze