% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  12pt,
]{book}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage{booktabs}
\usepackage{color}
\usepackage{tcolorbox}
\usepackage{float}
\graphicspath{ {images/} }

\newenvironment{rmdremind}
  {\begin{tcolorbox}[width=\textwidth, 
                     colback = {white}, 
                     title = {\textbf{Remember}}, 
                     colbacktitle = lightgray,
                     coltitle = black]
  \begin{includegraphics}[scale = 1]{remind.png}
  \begin{itemize}}
  {\end{itemize}
  \end{includegraphics}
  \end{tcolorbox}}

\newenvironment{rmdnote}
  {\begin{tcolorbox}[width=\textwidth, 
                     colback = {white}, 
                     title = {\textbf{Note}}, 
                     colbacktitle = lightgray,
                     coltitle = black]
  \begin{includegraphics}[scale = 1]{pencil.png}}
  {\end{includegraphics}
  \end{tcolorbox}}
  
\newenvironment{rmdexercise}
  {\begin{tcolorbox}[width=\textwidth, 
                     colback = {white}, 
                     title = {\textbf{Exercise}}, 
                     colbacktitle = lightgray,
                     coltitle = black]
  \begin{includegraphics}[scale = 1]{exercise.png}}
  {\end{includegraphics}
  \end{tcolorbox}}
  
\newenvironment{rmdinfo}
  {\begin{tcolorbox}[width=\textwidth, 
                     colback = {white}, 
                     title = {\textbf{Info}}, 
                     colbacktitle = lightgray,
                     coltitle = black]
  \begin{includegraphics}[scale = 1]{info.png}}
  {\end{includegraphics}
  \end{tcolorbox}}  
  
\newenvironment{rmdwarning}
  {\begin{tcolorbox}[width=\textwidth, 
                     colback = {white}, 
                     title = {\textbf{Warning}}, 
                     colbacktitle = lightgray,
                     coltitle = black]
  \begin{includegraphics}[scale = 1]{warning.png}}
  {\end{includegraphics}
  \end{tcolorbox}}

\newenvironment{rmddownload}
  {\begin{tcolorbox}[width=\textwidth, 
                     colback = {white}, 
                     title = {\textbf{Download}}, 
                     colbacktitle = lightgray,
                     coltitle = black]
  \begin{includegraphics}[scale = 1]{download.png}}
  {\end{includegraphics}
  \end{tcolorbox}}
   
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage[]{natbib}
\bibliographystyle{apalike}
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={University of Oxford International Health and Tropical Medicine},
  pdfauthor={Proochista Ariana and Ernest Guevarra},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{University of Oxford International Health and Tropical Medicine}
\author{Proochista Ariana and Ernest Guevarra}
\date{2023-01-26}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{1}
\tableofcontents
}
\hypertarget{open-science-and-reproducible-research-handbook}{%
\chapter*{Open Science and Reproducible Research Handbook}\label{open-science-and-reproducible-research-handbook}}
\addcontentsline{toc}{chapter}{Open Science and Reproducible Research Handbook}

\includegraphics{images/ihtm_small.png}

\hypertarget{introduction}{%
\chapter{Introduction}\label{introduction}}

\hypertarget{all-about-r}{%
\section{All about R}\label{all-about-r}}

\href{https://r-project.org}{R} is a language and environment for statistical computing and graphics. It is a \href{https://en.wikipedia.org/wiki/GNU}{GNU} project which is similar to the \href{https://en.wikipedia.org/wiki/S_(programming_language)}{S language and environment} which was developed at Bell Laboratories (formerly AT\&T, now Lucent Technologies) by John Chambers and colleagues. R can be considered as a different implementation of S. There are some important differences, but much code written for S runs unaltered under R.

\href{https://r-project.org}{R} provides a wide variety of statistical (linear and nonlinear modelling, classical statistical tests, time-series analysis, classification, clustering, etc.) and graphical techniques, and is highly extensible. The S language is often the vehicle of choice for research in statistical methodology, and R provides an Open Source route to participation in that activity.

One of \href{https://r-project.org}{R}'s strengths is the ease with which well-designed publication-quality plots can be produced, including mathematical symbols and formulae where needed. Great care has been taken over the defaults for the minor design choices in graphics, but the user retains full control.

R is available as Free Software under the terms of the Free Software Foundation's GNU General Public License in source code form. It compiles and runs on a wide variety of UNIX platforms and similar systems (including FreeBSD and Linux), Windows and MacOS.

R is unique in that it is not general-purpose. It does not compromise by trying to do a lot of things. It does a few things very well, mainly statistical analysis and data visualization. While you can find data analysis and machine learning libraries for languages like \href{https://www.python.org/}{Python}, R has many statistical functionalities built into its core. No third-party libraries are needed for much of the core data analysis you can do with the language.

But even with this specific use case, it is used in every industry you can think of because a modern business runs on data. Using past data, data scientists and data analysts can determine the health of a business and give business leaders actionable insights into the future of their company.

Just because R is specifically used for statistical analysis and data visualization doesn't mean its use is limited. It's actually quite popular, ranking 12th in the \href{https://www.tiobe.com/tiobe-index/}{TIOBE index} of the most popular programming languages.

Academics, scientists, and researchers use R to analyze the results of experiments. In addition, businesses of all sizes and in every industry use it to extract insights from the increasing amount of daily data they generate.

\hypertarget{open-and-reproducible-science}{%
\section{Open and reproducible science}\label{open-and-reproducible-science}}

Open Science is the practice of science in such a way that others can collaborate and contribute, where research data, lab notes and other research processes are freely available, under terms that enable reuse, redistribution and reproduction of the research and its underlying data and methods. Reproducible research means that research data and code are made available so that others are able to reach the same results as are claimed in scientific outputs. Closely related is the concept of replicability, the act of repeating a scientific methodology to reach similar conclusions. These concepts are core elements of empirical research.

This lecture series is designed to give Oxford IHTM students a foundational understanding and appreciation of the pillars of Open Science more broadly and within that the concepts, methods and tools for Reproducible Research more specifically. To further the students' learning, practical examples and exercises will be discussed and walked through using the R language for statistical computing as a way to practically demonstrate these concepts.

\hypertarget{install-r}{%
\chapter{Installing R and RStudio}\label{install-r}}

\hypertarget{setup-for-windows-machines}{%
\section{Setup for Windows machines}\label{setup-for-windows-machines}}

\hypertarget{install-r-for-windows-machines}{%
\subsection{Install R for Windows machines}\label{install-r-for-windows-machines}}

Following is a simple guide to installing R and RStudio and other required software on Windows machines.

Important that R is installed first. R is the main software and is needed for RStudio to work properly. R should always be installed first.

Go to \url{https://cran.r-project.org}

Click on link that says Download R for Windows

Then click on the link that says install R for the first time

Then click on Download R-4.X.X for Windows. This will start the download process.

Once downloaded, go to the \texttt{.exe} file in your \texttt{Downloads} folder, double-click and follow all the install prompts, selecting recommended options all the time

\hypertarget{install-rstudio}{%
\subsection{Install RStudio}\label{install-rstudio}}

This step requires that step 1 has been done and was successful.

Go to \url{https://posit.co/download/rstudio-desktop/}

Select the download specific for your Windows machine.

Once downloaded, double-click on \texttt{.exe} file downloaded to your \texttt{Downloads} folder and then follow all install prompts, always selecting recommended options.

\hypertarget{install-rtools}{%
\subsection{\texorpdfstring{Install \texttt{Rtools}}{Install Rtools}}\label{install-rtools}}

For the things that you will be taught in the \textbf{Open and Reproducibile Science Lecture Series}, you we will need to expand the installation of R by installing the \texttt{Rtools} software from R.

The download link is \url{https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html} if you have installed R version 4.2.0 (or higher).

Once you have downloaded the \texttt{.exe} file, double-click on the \texttt{.exe} file and follow all install prompts. Choose all the recommended options.

\hypertarget{install-git-for-windows}{%
\subsection{Install Git for Windows}\label{install-git-for-windows}}

For the things that you will be taught in the \textbf{Open and Reproducibile Science Lecture Series}, you we will need to install \textbf{Git for Windows}.

If your machine is 64-bit machine (most likely the case if your computer is new and running Windows 10 or later) -

Use this download link - \url{https://github.com/git-for-windows/git/releases/latest} - to download the latest version of git. Make sure to choose the appropriate download for your machine (i.e., if you have a 64-bit machine then select the download for 64-bit machines; if you have a 32-bit machine then select the download for 32-bit machines)

Once you have downloaded the \texttt{.exe} file, double-click it and then follow all install prompts. Choose all recommended options.

\hypertarget{setup-for-macos-machines}{%
\section{Setup for macOS machines}\label{setup-for-macos-machines}}

\hypertarget{install-r-for-macos-machines}{%
\subsection{Install R for macOS machines}\label{install-r-for-macos-machines}}

Following is a simple guide to installing R and RStudio and other required software on macOS machines.

Important that R is installed first. R is the main software and is needed for RStudio to work properly. R should always be installed first.

Go to \url{https://cran.r-project.org}

Click on link that says Download R for macOS

You will have two choices of R versions to install. Make sure to install the appropriate version for your macOS version (Apple Silicon vs Apple Intel version). Click on the download link for your macOS version. This will start the download process of the \texttt{.pkg} file specific for installing in macOS computers.

Once downloaded, go to the \texttt{.pkg} file in your \texttt{Downloads} folder, double-click and follow all the install prompts, selecting recommended options all the time

\hypertarget{install-rstudio-1}{%
\subsection{Install RStudio}\label{install-rstudio-1}}

This step requires that step 1 has been done and was successful.

Go to \url{https://posit.co/download/rstudio-desktop/}

Select the download specific for your macOS machine.

Once downloaded, double-click on \texttt{.dmg} file downloaded to your \texttt{Downloads} folder and then follow all install prompts, always selecting recommended options.

\hypertarget{install-git-for-macos}{%
\subsection{Install git for macOS}\label{install-git-for-macos}}

For the things that you will be taught in the \textbf{Open and Reproducibile Science Lecture Series}, you we will need to install \textbf{git for macOS}. Apple machines are already pre-installed with \texttt{git} but it is usually an Apple specific version of git and tends to be older and not configured in the way we need it. So we need to install another version of it that comes with Apple's \texttt{Xcode\ command\ line\ tools}.

To install, go to the macOS terminal and type the following command:

\begin{verbatim}
xcode-select --install
\end{verbatim}

\hypertarget{intro-r}{%
\chapter{Introduction to R and RStudio}\label{intro-r}}

\hypertarget{what-r}{%
\section{What is R?}\label{what-r}}

\texttt{R} is a system for data manipulation, calculation, and graphics. It provides:

\begin{itemize}
\item
  Facilities for data handling and storage
\item
  A large collection of tools for data analysis
\item
  Graphical facilities for data analysis and display
\item
  A simple but powerful programming language
\end{itemize}

\texttt{R} is often described as an environment for working with data. This is in contrast to a statistical \emph{package} which is a collection of very specific tools. \texttt{R} is not strictly a statistics system but a system that provides many classical and modern statistical procedures as part of a broader data-analysis tool. This is an important difference between \texttt{R} and other statistical systems. In \texttt{R} a statistical analysis is usually performed as a series of steps with intermediate results being stored in objects. Systems such as \texttt{SPSS} and \texttt{SAS} provide copious output from (e.g.) a regression analysis whereas \texttt{R} will give minimal output and store the results of a fit for subsequent interrogation or use with other \texttt{R} functions. This means that \texttt{R} can be tailored to produce exactly the analysis and results that you want rather than produce an analysis designed to fit all situations.

\texttt{R} is a language based product. This means that you interact with \texttt{R} by typing commands such as:

~

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(SEX, LIFE)}
\end{Highlighting}
\end{Shaded}

~

rather than by using menus, dialog boxes, selection lists, and buttons. This may seem to be a drawback but it means that the system is considerably more flexible than one that relies on menus, buttons, and boxes. It also means that every stage of your data management and analysis can be recorded and edited and re-run at a later date. It also provides an audit trail for quality control purposes.

\texttt{R} is available under UNIX (including Linux), the Macintosh operating system OS X, and Microsoft Windows. The method used for starting \texttt{R} will vary from system to system. On UNIX systems you may need to issue the \texttt{R} command in a terminal session or click on an icon or menu option if your system has a windowing system. On Macintosh systems \texttt{R} will be available as an application but can also be run in a terminal session. On Microsoft Windows systems there will usually be an icon on the Start menu or the desktop.

\hypertarget{why-r}{%
\section{Why use R?}\label{why-r}}

\texttt{R} is an open source system and is available under the \emph{GNU general public license} (GPL) which means that it is available for free but that there are some restrictions on how you are allowed to distribute the system and how you may charge for bespoke data analysis solutions written using the \texttt{R} system. Details of the general public license are available from \url{http://www.gnu.org/copyleft/gpl.html}.

\texttt{R} is available for download from \url{http://www.r-project.org/}.

This is also the best place to get extension packages and documentation. You may also subscribe to the \texttt{R} mailing lists from this site. \texttt{R} is supported through mailing lists. The level of support is at least as good as for commercial packages. It is typical to have queries answered in a matter of a few hours.

Even though \texttt{R} is a free package it is more powerful than most commercial packages. Many of the modern procedures found in commercial packages were first developed and tested using \texttt{R} or \textbf{S-Plus} (the commercial equivalent of \texttt{R}).

\hypertarget{what-rstudio}{%
\section{What is RStudio}\label{what-rstudio}}

RStudio is an \textbf{integrated development environment (IDE)} for R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management.

RStudio is available in open source and commercial editions and runs on the desktop (Windows, Mac, and Linux) or in a browser connected to RStudio Server or RStudio Workbench (Debian/Ubuntu, Red Hat/CentOS, and SUSE Linux).

RStudio IDE Overview

\hypertarget{intro-git}{%
\chapter{Introduction to git and GitHub}\label{intro-git}}

\hypertarget{all-about-git}{%
\section{All about git}\label{all-about-git}}

\texttt{git} is a version control system for software development. It allows developers to keep track of changes made to their code and collaborate with other developers on a project. \texttt{git} also allows for easy rollbacks and branch management. It is widely used in the software industry and is considered one of the best version control systems available.

\texttt{git} was developed by Linus Torvalds in 2005. He created \texttt{git} as a replacement for the proprietary version control system he was using at the time. The development of \texttt{git} was driven by the need for a distributed version control system, which allows multiple developers to work on a project simultaneously, without the need for a central server. Linus Torvalds is also known for creating the Linux operating system kernel.

To use \texttt{git} in your machines, you will need to install it as described in the previous chapter (Chapter \ref{install-r}).

\hypertarget{all-about-github}{%
\section{All about GitHub}\label{all-about-github}}

\href{https://github.com}{GitHub} is a web-based platform that provides hosting for software development and a community of developers to collaborate, share and learn from each other. It is built on top of \texttt{git}, which is the version control system used for managing and tracking changes to the code. Developers can use GitHub to store and manage their code, collaborate with other developers, and track and manage issues and bugs. It also provides tools for code review, project management, and documentation. It is widely used by developers and organizations to host and share code, as well as to build and maintain open-source software.

GitHub is not a software you need to install. Rather it is a remote or cloud-based server that holds its users' code versioned using the \texttt{git} version control system and to which a user's local, git-versioned code syncs/communicates with.

A good illustration of the \texttt{git} and \texttt{GitHub} relationship can be viewed below:

\includegraphics{images/git_and_github01b.png}

To use GitHub, you will need create an account at \url{https://github.com}.

\hypertarget{creating-a-github-account}{%
\subsection{Creating a GitHub account}\label{creating-a-github-account}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Head to \url{https://github.com}
\item
  On the upper right hand corner of the page, click on \textbf{Sign-up} button
\end{enumerate}

\includegraphics{images/github_account1.png}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  You will be then prompted to provide an email address to register your account with.
\end{enumerate}

\includegraphics{images/github_account2.png}

With regard to the email address to use for creating a GitHub account, a best practice recommendation is to use an email address that you will have access to all the time. Email addresses such as those for school (if you are a student) or for your current work may not always be the best email address to use as these email addresses tend to be time-limited (i.e., you lose the email address once you graduate or once you leave your current work).

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  You will then be prompted for a password.
\end{enumerate}

\includegraphics{images/github_account2.png}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Then follow all other prompts after this including confirmation of your email and creating a GitHub username.
\end{enumerate}

With regard to creating/selecting a GitHub username, following are some best practice recommendations:

\begin{itemize}
\item
  Incorporate your actual name! People like to know who they're dealing with. Also makes your username easier for people to guess or remember.
\item
  Pick a username you will be comfortable revealing to your future boss and/or to future collaborators.
\item
  Shorter is better than longer.
\item
  Be as unique as possible in as few characters as possible. In some settings GitHub auto-completes or suggests usernames.
\item
  Make it timeless. Don't highlight your current university, employer, or place of residence.
\item
  Avoid the use of upper vs.~lower case to separate words. We highly recommend all lowercase. GitHub treats usernames in a case insensitive way, but using all lowercase is kinder to people doing downstream regular expression work with usernames, in various languages. A better strategy for word separation is to use a hyphen \texttt{-}.
\item
  You can change your username later, but better to get this right the first time.
\end{itemize}

\url{https://help.github.com/articles/changing-your-github-username/}

\url{https://help.github.com/articles/what-happens-when-i-change-my-username/}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{5}
\tightlist
\item
  Once you have created a GitHub account, please do share your username to the lecture seriese presenter so he can add your username to the Oxford IHTM GitHub account and add you to the Oxford IHTM GitHub Classroom.
\end{enumerate}

\hypertarget{connect-rstudio-github}{%
\chapter{Connecting RStudio with GitHub}\label{connect-rstudio-github}}

Once RStudio is installed and a GitHub account has been created and registered, the final step in the R, RStudio, git, and GitHub dance is to create git-related settings on your machine that will identify you as a unique/specific git user and then creating a GitHub \textbf{personal access token (PAT)} which will serve as the key or proof that you will use to identify yourself as the git user you claim to be whenever you try to syn/connect to your GitHub account via RStudio or any other tool on your local computer.

Follow are the steps you will need to perform:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  On your local machine, open RStudio and then select the \texttt{Terminal} tab in the console pane.
\end{enumerate}

The \texttt{Terminal} is the tool used to interface with your computer through commands written in a programming language called \texttt{bash}. Most of you would have never used the \texttt{Terminal} because the computers you use have different kinds of software built-in that provide a \textbf{graphical user interface (GUI)} that you can use to perform operations and tasks.

RStudio comes with the \texttt{Terminal} tool built in and usually is already available from the console pane as a separate table along side the R console (see below). By default, whenever you open RStudio, this tab for the \texttt{Terminal} tool should already be available.

If if is not present, you can easily open a new \texttt{Terminal} tab in the console pane by going to the RStudio menu ribbon and clicking on:

\begin{verbatim}
Tools --> Terminal --> New Terminal
\end{verbatim}

or you can use the \texttt{ALT\ +\ SHIFT\ +\ R} keyboard shortcut.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Introduce yourself to git
\end{enumerate}

In this step, you are basically going to issue a set of commands to your computer to save and store specific settings for the \texttt{git} software that you have installed.

Specifically, you are going to let git know who you are (your name) and what your email address is \textbf{that is associated with your GitHub account}.

The commands will be issued on the \texttt{Terminal} that we mentioned in step 1. The commands are:

\begin{verbatim}
git config --global user.name 'Jane Doe'
git config --global user.email 'jane@example.com'
\end{verbatim}

Make sure to supply your full proper name (and not your username you created in GitHub).

Make sure that the email you provide is the email address you used to register and create an account with GitHub.

Unless there was an error in your syntax, you should not expect any output on the \texttt{Terminal} after you issue the commands. To check that your name and email address have been recorded and/or that the name and email address recorded is correct, you can issue the following command:

\begin{verbatim}
git config --global --list
\end{verbatim}

Here is an example of what you will see after issue this command:

\begin{verbatim}
$ git config --global --list

user.name=Jane Doe
user.email=jane@example.com
\end{verbatim}

Check this output to what you expect it to be specified as. If the information is correct, then you've completed this step. If you need to correct any of this information, then repeat this step making sure that the name and email address you provide is correct.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Create a GitHub personal access token (PAT)
\end{enumerate}

Now that you have introduced yourself to the \texttt{git} that is installed in your local machine/computer, you should now visit GitHub on a browser (\url{https://github.com}) and create a \textbf{personal access token (PAT)}.

When you communicate/sync/interact with a remote git server, such as GitHub, you have to include credentials in the communication you are sending. These credentials prove that you are a specific GitHub user, who's allowed to do whatever you're asking to do.

\texttt{git} can communicate with a remote server using one of two protocols, HTTPS or SSH, and the different protocols use different credentials.

Here we describe the credential setup for the HTTPS protocol, which is what we recommend if you have no burning reason to pick SSH. With HTTPS, we will use a \textbf{personal access token (PAT)}.

Please note that the \textbf{personal access token (PAT)} is not the same as the password you provided when registering for your GitHub account. Also, in performing a connection to GitHub via HTTPS protocol, your password is not an acceptable credential for communicating with GitHub as a server.

To create a GitHub \textbf{personal access token (PAT)}, you need to:

3a. Go to Settings from your GitHub account menu

Login to your GitHub account. On the upper right hand corner of the GitHub page you will see your account icon. Click on it to reveal a drop down menu as shown below. Select the \textbf{Settings} option.

\includegraphics{images/github_pat2.png}

3b. From Settings navigate to Developer Settings

In the \textbf{Settings} page, find the \textbf{Developer Settings} option on the left hand sidebar as shown below:

\includegraphics{images/github_pat3.png}

3c. From Developer Settings navigate to Personal Access Token

In the \textbf{Developer Settings} page, find the \textbf{Personal Access Token} option on the left hand sidebar as shown below:

\includegraphics{images/github_pat4.png}

3d. Select Tokens (classic)

\includegraphics{images/github_pat5.png}

3e. Click on Generate new token

\includegraphics{images/github_pat7.png}

3f. Select Generate new token (classic)

\includegraphics{images/github_pat8.png}

3g. Give your token a name

\includegraphics{images/github_pat9.png}

The token name should be short but descriptive of the where or how you will use the token. Since we are using this to connect and allow communication between RStudio and GitHub, \textbf{RStudio} can be a good name that would remind you that this is what you are using to secure the connection/communication between your RStudio and your GitHub account.

3f. Set an expiry date for the token

\includegraphics{images/github_pat9.png}

By default, GitHub will set a \textbf{30 day validity} for any new token created. Clicking on the option menu will show the other possible time periods to choose from including \textbf{No expiry date}.

It is best practice to assign an expiry date for security tokens such as the GitHub PAT. And a 30 day validity is standard practice. However, in reality, it is cumbersome to be creating new tokens frequently and for beginners, having to go through these steps again can be quite a chore. For the purposes of this lecture series, we would recommend setting the expiry for about 90 days to cover the whole period and then as a group, we'll have a \textbf{renew GitHub PAT party} on our last session.

3g. Set scopes

\includegraphics{images/github_pat10.png}

Scopes are the types of permissions that you are attaching the token you are generating. This is again a security feature as takens should only be given specific and limited permissions based on what you intend the token to be used for. It is not good practice to give a token complete or unlimited permissions as you are exposing your account to high risk if and when your token gets compromised.

For general R users, the following scopes are currently recommended:

\begin{itemize}
\tightlist
\item
  repo
\item
  workflow
\item
  gist
\item
  user
\end{itemize}

3h. Click on Generate token

\includegraphics{images/github_pat11.png}

After clicking you will now see a long string of characters and numbers which is your GitHub PAT. It is important to remember that once you see the generated GitHub PAT, you should copy this right away and store it securely. Treat your GitHub PAT in the same way you would treat your password for online accounts. The best way to securely store the GitHub PAT is using a password manager (LastPass, 1Password, BitWarden). If you have a macOS computer, you can save your GitHub PAT into your computer's keychain.

Non-secure password/token storage practices that has been done by other students before are:

\begin{itemize}
\tightlist
\item
  Email their password/token to themselves
\end{itemize}

If you are using free email services such as Gmail, then this is a hihly non-secure method. Others use their University of Oxford email address and argue that this is secure compared to using the free email services. Whilst it is true that a university email account is more secure, email communications and email storage is still one of the most vulnerable places to keep something that is meant to be kept secret.

\begin{itemize}
\item
  Paste the token into a Word document and save in personal computer with the filename GITHUB\_PAT.docx
\item
  Paste the token into a Word document and save in Dropbox or in Google Drive
\end{itemize}

Please \textbf{AVOID} these methods.

\hypertarget{write-functions}{%
\chapter{Writing functions}\label{write-functions}}

For this topic, we will use data on weight and height to calculate body mass index. As a refresher, body mass index is calculated as follows:

\[ \text{Body mass index} ~=~ \frac{weight ~ (kgs)}{height ~ (m) ^ 2} \]
For this topic on writing functions in R, we will use BMI as an example to explore and demonstrate how we can create our own functions in R.

Let's say for example that you have been doing a research on children aged 11 years and older in 3 schools and you have collected the following data:

\textbf{School 1516}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{school1516}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     school sex ageMonths weight height
## 427   1516   1       138   24.5  126.0
## 428   1516   1       150   28.3  136.3
## 429   1516   1       162   32.2  143.5
## 430   1516   1       162   32.7  143.5
## 431   1516   1       150   28.6  137.0
## 432   1516   2       138   26.5  134.0
## 433   1516   1       150   29.9  139.2
## 434   1516   1       150   30.0  139.5
## 435   1516   1       162   34.0  148.0
## 436   1516   1       138   25.4  135.7
## 437   1516   1       150   32.3  143.0
## 438   1516   2       174   38.3  153.5
## 439   1516   2       162   41.6  151.0
## 440   1516   1       150   30.7  145.0
## 441   1516   2       186   46.8  155.2
## 442   1516   1       186   46.6  163.4
## 443   1516   1       150   33.5  145.5
## 444   1516   1       186   47.0  164.0
## 445   1516   1       174   41.1  159.5
## 446   1516   2       162   39.1  152.2
## 447   1516   2       174   40.9  155.5
## 448   1516   2       162   39.7  153.0
## 449   1516   2       162   40.9  153.2
## 450   1516   1       150   34.2  147.5
## 451   1516   2       150   41.8  149.4
## 452   1516   1       138   28.0  141.5
## 453   1516   1       138   30.0  142.0
## 454   1516   1       138   33.1  142.0
## 455   1516   1       186   46.1  167.5
## 456   1516   1       150   36.2  149.0
## 457   1516   2       162   47.4  156.0
## 458   1516   1       150   30.3  150.2
## 459   1516   2       150   36.4  152.1
## 460   1516   2       150   36.4  155.0
## 461   1516   2       150   44.1  155.0
## 462   1516   2       162   42.3  160.1
## 463   1516   2       179   50.4  163.5
## 464   1516   1       150   37.6  155.0
## 465   1516   2       138   36.0  154.5
## 466   1516   2       138   46.1  156.0
\end{verbatim}

\textbf{School 1522}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{school1522}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     school sex ageMonths weight height
## 646   1522   1       203   30.6  140.5
## 647   1522   1       174   30.8  140.0
## 648   1522   1       162   29.3  136.3
## 649   1522   1       150   24.0  132.0
## 650   1522   1       150   28.1  132.1
## 651   1522   2       150   27.2  134.9
## 652   1522   1       162   34.2  139.2
## 653   1522   1       150   25.5  134.2
## 654   1522   1       138   24.6  129.0
## 655   1522   1       174   36.4  147.5
## 656   1522   1       150   28.7  137.5
## 657   1522   1       186   45.8  155.6
## 658   1522   1       174   36.3  151.6
## 659   1522   1       150   31.0  139.5
## 660   1522   1       138   29.0  134.3
## 661   1522   1       179   38.3  155.5
## 662   1522   2       138   31.3  138.4
## 663   1522   1       162   36.5  148.8
## 664   1522   1       155   36.8  145.2
## 665   1522   1       138   28.3  136.8
## 666   1522   1       138   26.8  137.3
## 667   1522   2       138   32.6  141.4
## 668   1522   2       138   31.9  143.0
## 669   1522   1       174   42.6  160.7
## 670   1522   2       198   57.8  158.0
## 671   1522   2       162   43.9  153.5
## 672   1522   2       150   35.1  150.6
## 673   1522   2       186   52.6  159.6
## 674   1522   2       150   45.1  152.8
## 675   1522   2       138   34.6  147.2
## 676   1522   2       150   45.3  153.1
## 677   1522   1       186   51.8  170.2
## 678   1522   2       150   57.1  154.2
## 679   1522   2       138   33.5  149.2
## 680   1522   1       150   36.3  154.1
## 681   1522   1       174   44.0  169.1
## 682   1522   2       150   44.5  158.3
## 683   1522   2       150   51.5  159.1
## 684   1522   2       138   47.4  157.8
## 685   1522   2       138   36.8  158.5
## 686   1522   2       138   52.0  161.0
\end{verbatim}

\textbf{School 1525}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{school1525}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     school sex ageMonths weight height
## 752   1525   1       186   26.2    137
## 753   1525   1       186   32.7    138
## 754   1525   1       150   25.9    130
## 755   1525   1       162   30.4    137
## 756   1525   2       138   24.4    129
## 757   1525   2       138   23.8    130
## 758   1525   1       150   26.1    133
## 759   1525   1       150   26.4    135
## 760   1525   1       174   35.1    148
## 761   1525   1       162   28.7    142
## 762   1525   1       150   28.0    136
## 763   1525   1       174   34.0    149
## 764   1525   1       186   40.6    155
## 765   1525   2       150   35.8    142
## 766   1525   1       150   35.4    140
## 767   1525   2       138   27.8    137
## 768   1525   2       138   28.2    137
## 769   1525   2       138   29.7    139
## 770   1525   2       138   30.9    139
## 771   1525   1       138   28.2    137
## 772   1525   2       138   26.2    140
## 773   1525   2       138   26.6    140
## 774   1525   1       138   27.2    138
## 775   1525   2       138   27.0    141
## 776   1525   1       150   31.3    145
## 777   1525   2       162   33.9    152
## 778   1525   2       162   42.0    153
## 779   1525   2       185   38.3    157
## 780   1525   2       138   31.0    145
## 781   1525   2       138   32.3    145
## 782   1525   1       139   35.1    144
## 783   1525   2       150   36.4    152
## 784   1525   2       138   32.7    147
## 785   1525   1       174   44.9    166
## 786   1525   2       138   32.2    148
## 787   1525   2       138   36.4    148
## 788   1525   1       138   31.4    146
## 789   1525   2       138   45.0    149
## 790   1525   2       162   49.4    160
## 791   1525   2       138   34.3    150
## 792   1525   1       138   30.0    148
## 793   1525   2       150   37.0    156
## 794   1525   2       162   52.2    165
## 795   1525   2       138   42.9    158
\end{verbatim}

In this dataset, the units of the height measurement is in centimetres.

Using what we have learned earlier on calculating BMI using R, I can perform the following R commands to get the BMI for each child in each of the schools:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1516}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}

\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1522}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}

\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1525}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

Because the commands are repetitive, I can easily copy and paste my initial line of code to calculate BMI for children in school 1516 and then just change the object names accordingly to calculate the BMI for children in the two other schools.

When I run these lines of code, I get the following results:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1516}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 15.43210 15.23333 15.63695 15.87976 15.23789 14.75830 15.43095 15.41604 15.52228 13.79349 15.79539 16.25481 18.24481 14.60166
## [15] 19.42954 17.45347 15.82409 17.47472 16.15550 16.87903 16.91463 16.95929 17.42632 15.71962 18.72730 13.98444 14.87800 16.41539
## [29] 16.43128 16.30557 19.47732 13.43083 15.73414 15.15088 18.35588 16.50280 18.85363 15.65036 15.08153 18.94313
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1522}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in school1522$weight/(school1516$height/100)^2: longer object length is not a multiple of shorter object length
\end{verbatim}

\begin{verbatim}
##  [1] 19.27438 16.57903 14.22865 11.65487 14.97150 15.14814 17.65012 13.10363 11.23083 19.76704 14.03492 19.43787 15.92035 14.74435
## [15] 12.03967 14.34481 14.78490 13.57079 14.46527 12.21679 11.08343 13.92627 13.59168 19.58058 25.89564 21.92561 17.40726 26.08609
## [29] 16.07485 15.58488 18.61440 22.96095 24.68185 13.94381 15.10926 17.16604 16.64656 21.43600 19.85735 15.12163 32.75384
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1525}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in school1525$weight/(school1516$height/100)^2: longer object length is not a multiple of shorter object length
\end{verbatim}

\begin{verbatim}
##  [1] 16.50290 17.60176 12.57755 14.76284 13.00016 13.25462 13.46983 13.56612 16.02447 15.58555 13.69260 14.42986 17.80624 17.02735
## [15] 14.69670 10.41216 13.32058 11.04253 12.14611 12.17362 10.83529 11.36315 11.58914 12.41023 14.02307 16.93116 20.82920 18.99425
## [29] 11.04923 14.54889 14.42308 16.13472 14.13479 18.68887 13.40271 14.20099 11.74611 18.73049 20.69522 14.09435 18.89645 19.91636
## [43] 25.34934 20.83308
\end{verbatim}

The calculation for the BMI of children in school 1516 seems to have completed without issues and a vector of BMI results have been produced. However, for school 1522 and school 1525, there is a warning saying:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Warning in school1522$weight/(school1516$height)\^{}2: longer object length is not a multiple}
\DocumentationTok{\#\# of shorter object length}
\end{Highlighting}
\end{Shaded}

Although a result has been provided, the warning gives me an indication that someting is not quite right with my calculation and when I inspect further, I notice that in my formula for school 1522 and for school 1525, my denominator is still using data for school 1516 and this is most likely what is causing the warning message.

So, to correct this I go back to my lines of code and edit the denominators for school 1522 and school 1525 as follows:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1516}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}

\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1522}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1522}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}

\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1525}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1525}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

which gives me:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1516}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 15.43210 15.23333 15.63695 15.87976 15.23789 14.75830 15.43095 15.41604 15.52228 13.79349 15.79539 16.25481 18.24481 14.60166
## [15] 19.42954 17.45347 15.82409 17.47472 16.15550 16.87903 16.91463 16.95929 17.42632 15.71962 18.72730 13.98444 14.87800 16.41539
## [29] 16.43128 16.30557 19.47732 13.43083 15.73414 15.15088 18.35588 16.50280 18.85363 15.65036 15.08153 18.94313
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1522}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1522}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 15.50132 15.71429 15.77161 13.77410 16.10277 14.94669 17.65012 14.15908 14.78277 16.73082 15.18017 18.91674 15.79459 15.92991
## [15] 16.07852 15.83937 16.34076 16.48493 17.45479 15.12217 14.21653 16.30492 15.59978 16.49597 23.15334 18.63150 15.47594 20.65000
## [29] 19.31656 15.96837 19.32626 17.88178 24.01416 15.04898 15.28626 15.38741 17.75817 20.34543 19.03550 14.64837 20.06095
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{school1525}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1525}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 13.95919 17.17076 15.32544 16.19692 14.66258 14.08284 14.75493 14.48560 16.02447 14.23329 15.13841 15.31463 16.89906 17.75441
## [15] 18.06122 14.81166 15.02477 15.37188 15.99296 15.02477 13.36735 13.57143 14.28271 13.58081 14.88704 14.67278 17.94182 15.53816
## [29] 14.74435 15.36266 16.92708 15.75485 15.13258 16.29409 14.70051 16.61797 14.73072 20.26936 19.29687 15.24444 13.69613 15.20381
## [43] 19.17355 17.18475
\end{verbatim}

I now do not get the warning message and the expected length of BMI values for each school has now been produced.

From this short example above, we realise how tedious a task it is to type in the code above every time we need to calculate BMI. Also, it becomes even challenging to debug issues with the code because we have to review and edit (as needed) each iteration of the calculation to see where it may have gone wrong (especially when doing a cut and paste approach).

It would be better (and easier) to have a function that calculates and displays the BMI values automatically. Fortunately, \texttt{R} allows us to do just that.

The \texttt{function()} function allows us to create new functions in \texttt{R} with the following generic syntax:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{function\_name }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(argument1, argument2, ...) \{}
  \DocumentationTok{\#\# Your code here}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Using this template/generic syntax, we apply it to create a function called \texttt{calculate\_bmi} as follows:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{calculate\_bmi }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(weight, height) \{}
\NormalTok{  weight }\SpecialCharTok{/}\NormalTok{ height }\SpecialCharTok{\^{}} \DecValTok{2}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

We now have a function for calculating and outputing BMI values.

Let us now test it with our 3 sets of data:

\textbf{School 1516}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calculate\_bmi}\NormalTok{(}
  \AttributeTok{weight =}\NormalTok{ school1516}\SpecialCharTok{$}\NormalTok{weight,}
  \AttributeTok{height =}\NormalTok{ school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 15.43210 15.23333 15.63695 15.87976 15.23789 14.75830 15.43095 15.41604 15.52228 13.79349 15.79539 16.25481 18.24481 14.60166
## [15] 19.42954 17.45347 15.82409 17.47472 16.15550 16.87903 16.91463 16.95929 17.42632 15.71962 18.72730 13.98444 14.87800 16.41539
## [29] 16.43128 16.30557 19.47732 13.43083 15.73414 15.15088 18.35588 16.50280 18.85363 15.65036 15.08153 18.94313
\end{verbatim}

\textbf{School 1522}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calculate\_bmi}\NormalTok{(}
  \AttributeTok{weight =}\NormalTok{ school1522}\SpecialCharTok{$}\NormalTok{weight,}
  \AttributeTok{height =}\NormalTok{ school1522}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 15.50132 15.71429 15.77161 13.77410 16.10277 14.94669 17.65012 14.15908 14.78277 16.73082 15.18017 18.91674 15.79459 15.92991
## [15] 16.07852 15.83937 16.34076 16.48493 17.45479 15.12217 14.21653 16.30492 15.59978 16.49597 23.15334 18.63150 15.47594 20.65000
## [29] 19.31656 15.96837 19.32626 17.88178 24.01416 15.04898 15.28626 15.38741 17.75817 20.34543 19.03550 14.64837 20.06095
\end{verbatim}

\textbf{School 1525}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calculate\_bmi}\NormalTok{(}
  \AttributeTok{weight =}\NormalTok{ school1525}\SpecialCharTok{$}\NormalTok{weight,}
  \AttributeTok{height =}\NormalTok{ school1525}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 13.95919 17.17076 15.32544 16.19692 14.66258 14.08284 14.75493 14.48560 16.02447 14.23329 15.13841 15.31463 16.89906 17.75441
## [15] 18.06122 14.81166 15.02477 15.37188 15.99296 15.02477 13.36735 13.57143 14.28271 13.58081 14.88704 14.67278 17.94182 15.53816
## [29] 14.74435 15.36266 16.92708 15.75485 15.13258 16.29409 14.70051 16.61797 14.73072 20.26936 19.29687 15.24444 13.69613 15.20381
## [43] 19.17355 17.18475
\end{verbatim}

In our example here, the \texttt{calculate\_bmi()} function helped a little bit in making the code to calculate BMI for each student in each school more efficient. But the efficiency that functions provide become more evident when you need to make more complex operations. For example, what if you need to get the mean BMI for students in each school? Without a function, we will have to do the following script for each school:

\textbf{School 1516}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1516}
\NormalTok{bmi\_school1516 }\OtherTok{\textless{}{-}}\NormalTok{ school1516}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}

\DocumentationTok{\#\# Get the mean BMI for children in school 1516}
\NormalTok{mean\_bmi\_school1516 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(bmi\_school1516)}

\NormalTok{mean\_bmi\_school1516}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.28491
\end{verbatim}

\textbf{School 1522}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1522}
\NormalTok{bmi\_school1522 }\OtherTok{\textless{}{-}}\NormalTok{ school1522}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1522}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\^{}} \DecValTok{2}

\DocumentationTok{\#\# Get the mean BMI for children in school 1522}
\NormalTok{mean\_bmi\_school1522 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(bmi\_school1522)}

\NormalTok{mean\_bmi\_school1522}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.89955
\end{verbatim}

\textbf{School 1525}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Calculate BMI for children in school 1525}
\NormalTok{bmi\_school1525 }\OtherTok{\textless{}{-}}\NormalTok{ school1525}\SpecialCharTok{$}\NormalTok{weight }\SpecialCharTok{/}\NormalTok{ (school1525}\SpecialCharTok{$}\NormalTok{height) }\SpecialCharTok{\^{}} \DecValTok{2}

\DocumentationTok{\#\# Get the mean BMI for children in school 1525}
\NormalTok{mean\_bmi\_school1525 }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(bmi\_school1525)}

\NormalTok{mean\_bmi\_school1525}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.001564695
\end{verbatim}

As the operations/calculations we want to perform become more complex, the copy and paste method becomes more and more tedious. With the function approach, we can use the following:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{calculate\_mean\_bmi }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(weight, height) \{}
\NormalTok{  bmi }\OtherTok{\textless{}{-}}\NormalTok{ weight }\SpecialCharTok{/}\NormalTok{ height }\SpecialCharTok{\^{}} \DecValTok{2}
  
\NormalTok{  mean\_bmi }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(bmi)}
  
  \FunctionTok{return}\NormalTok{(mean\_bmi)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Applying the function to the datasets, we get:

\textbf{School 1516}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calculate\_mean\_bmi}\NormalTok{(}
  \AttributeTok{weight =}\NormalTok{ school1516}\SpecialCharTok{$}\NormalTok{weight,}
  \AttributeTok{height =}\NormalTok{ school1516}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.28491
\end{verbatim}

\textbf{School 1522}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calculate\_mean\_bmi}\NormalTok{(}
  \AttributeTok{weight =}\NormalTok{ school1522}\SpecialCharTok{$}\NormalTok{weight,}
  \AttributeTok{height =}\NormalTok{ school1522}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.89955
\end{verbatim}

\textbf{School 1525}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{calculate\_mean\_bmi}\NormalTok{(}
  \AttributeTok{weight =}\NormalTok{ school1525}\SpecialCharTok{$}\NormalTok{weight,}
  \AttributeTok{height =}\NormalTok{ school1525}\SpecialCharTok{$}\NormalTok{height }\SpecialCharTok{/} \DecValTok{100}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 15.64695
\end{verbatim}

\hypertarget{clone-repository}{%
\chapter{Cloning a GitHub repository into your local computer using RStudio}\label{clone-repository}}

This tutorial is a summary of the the instructions described here - \url{https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository}.

\hypertarget{copy-the-repository-url-of-the-repository-you-want-to-clone-from-github}{%
\section{Copy the repository URL of the repository you want to clone from GitHub}\label{copy-the-repository-url-of-the-repository-you-want-to-clone-from-github}}

\includegraphics{images/clone_step1.png}

7.1.1 Go to the GitHub page of the repository you own and click on the green button that is labeled code

7.1.2 Click on the copy to clipboard icon to copy the repository URL.

\hypertarget{go-to-rstudio-and-create-new-project}{%
\section{Go to RStudio and create new project}\label{go-to-rstudio-and-create-new-project}}

\includegraphics{images/clone_step2.png}

\hypertarget{choose-version-control}{%
\section{Choose Version Control}\label{choose-version-control}}

\includegraphics{images/clone_step3.png}

\hypertarget{select-git}{%
\section{Select Git}\label{select-git}}

\includegraphics{images/clone_step4.png}

\hypertarget{setup-repository-settings}{%
\section{Setup repository settings}\label{setup-repository-settings}}

\includegraphics{images/clone_step5.png}

7.5.1 Paste the repository URL you copied earlier.

7.5.2 The Project directory name should be specified already after you paste the repository URL. Use the suggested directory name.

7.5.3 Browse for the directory on your local computer where you want to save the files for the specified project.

7.5.4 Click on the \texttt{Create\ Project} button/icon.

You will now have the GitHub repository in your local computer.

\hypertarget{commit-and-push}{%
\chapter{Committing your changes and pushing them to GitHub}\label{commit-and-push}}

Following are the steps to take in committing your changes in RStudio and pushing them to GitHub.

\hypertarget{click-on-commit-in-the-git-tab-on-rstudio}{%
\section{\texorpdfstring{Click on \texttt{Commit} in the Git tab on RStudio}{Click on Commit in the Git tab on RStudio}}\label{click-on-commit-in-the-git-tab-on-rstudio}}

\includegraphics{images/commit_push_pull1.png}

\hypertarget{getting-changes-saved-and-push-to-github}{%
\section{Getting changes saved and push to GitHub}\label{getting-changes-saved-and-push-to-github}}

\includegraphics{images/commit_push_pull2.png}

8.2.1 Tick the box beside the file that has changed to stage the changes.

8.2.2 Write a commit message in the \texttt{Commit\ message} dialog box. In the commit message, describe the changes that you made.

8.2.3 Click on the \texttt{Commit} button.

8.2.4 Click on the \texttt{Push} button.

\hypertarget{initiate-a-pull-request}{%
\section{Initiate a pull request}\label{initiate-a-pull-request}}

8.3.1 Click on the \textbf{branches} link from your repository

\includegraphics{images/pull_request1.png}

8.3.2 Click on the \textbf{Make pull request} link on the appropriate branch

\includegraphics{images/pull_request2.png}

8.3.3 Enter a title for your pull request

\includegraphics{images/pull_request3.png}

Make the titel as short but as informative as possible

8.3.4 Add further description about the pull request (optional) and then click on \textbf{Create pull request} button

\includegraphics{images/pull_request4.png}

If you think more information will help the reviewer navigate through the changes you have made, use the comment box to add more details. This comments box can interpret Markdown syntax so you can format your text accordingly.

On the right hand side of the pull request page, you can set a specific reviewer for your pull request (recommended). Also, given that you are making this pull request, assign this pull request to you so you are notified of the progress of this pull request.

Then finally click on the \textbf{Create pull request} button

8.3.5 Wait for review

If the project has automated checks included, you will see that these checks will get initiated.

\includegraphics{images/pull_request5.png}

If there are no issues with the code, the automated checks should show that all checks have passed.

\includegraphics{images/pull_request6.png}

Wait for reviewer's feedback/comments. If reviewer request's changes, make changes to your code and then commit and push again (as above). If your project has automated checks, this will get triggered again within the same pull request. Your reviewer will be notified of the changes you have made and should review your work again. Once reviewer approves changes, you can then merge your work to the main branch.

\hypertarget{participate-projects}{%
\chapter{Participating in an existing R/RStudio project}\label{participate-projects}}

Following are the general steps to take when participating in an existing R/RStudio project that has been initiated and led by someone else.

The following diagram illustrates the steps in this process:

\includegraphics{images/git_process1.png}

\hypertarget{clone-the-project-to-your-local-machine}{%
\section{Clone the project to your local machine}\label{clone-the-project-to-your-local-machine}}

Cloning a project to your local machine is described in Chapter \ref{clone-repository}

\hypertarget{create-a-new-branch-from-the-main-branch}{%
\section{Create a new branch from the main branch}\label{create-a-new-branch-from-the-main-branch}}

Before making any changes to the project, create a new branch as follows:

\hypertarget{click-on-new-branch}{%
\subsection{\texorpdfstring{Click on \textbf{New Branch}}{Click on New Branch}}\label{click-on-new-branch}}

\includegraphics{images/git_branch1.png}

\hypertarget{name-the-new-branch}{%
\subsection{Name the new branch}\label{name-the-new-branch}}

\includegraphics{images/git_branch2.png}

Name the branch uniquely. The best way to name a branch will be based on how the team/person you are working with prefers to name branches. Some would like the branch name to succinctly describe the type of change that is being made. Some may ask you to name your branch with your username. Some may ask you to name your branch using coded values.

Once named, click on \textbf{Create}

You will now see the new branch in the list of branches

\includegraphics{images/git_branch3.png}

\hypertarget{code-and-make-changes-to-your-branch}{%
\section{Code and make changes to your branch}\label{code-and-make-changes-to-your-branch}}

Start coding and implement the changes you want to make or the changes that your collaborator/s asked you to make.

\hypertarget{commit-and-push-your-changes-and-initiate-a-pull-request}{%
\section{Commit and push your changes and initiate a pull request}\label{commit-and-push-your-changes-and-initiate-a-pull-request}}

After making changes, you should \textbf{commit and push} your changes. This process is described in Chapter \ref{commit-and-push}. Your code and your changes do not have to be complete already for your to commit and push changes. It is good practice to commit and push frequently (at least once a day usually at the end of your coding session). See this as similar to saving your work at multiple stages.

Once your code and the changes you want to make are complete (and ideally that they are working correctly on your local machine), and that you are ready to have your work reviewed, you can now make a \textbf{pull request}. This process is also described in Chapter \ref{commit-and-push}.

\hypertarget{merge-pull-request}{%
\section{Merge pull request}\label{merge-pull-request}}

Once your chosen reviewer has seen your work, they may ask you to make changes based on what they see with your code. If so, then start coding again on the same branch and address the reviewers comments, *commit** those changes and *push\textbf{ the changes to your remote repository. Your changes will push into the same existing open }pull request** that is waiting approval. The reviewer can then view your changes and make the necessary feedback.

Once reviewer approves your changes, they may either merge your pull request themselves or they may let you know in their feedback that they are happy with your changes and that you can now merge your pull request. If so, then click on the \textbf{Merge pull request} button.

Your changes have now been integrated into the main branch of the project.

\hypertarget{initiate-projects}{%
\chapter{Initiating an R/RStudio project}\label{initiate-projects}}

Following is a diagram of the steps in initiating your own R/RStudio project.

\includegraphics{images/git_process2.png}

\hypertarget{create-a-new-project-in-rstudio}{%
\section{1. Create a new project in RStudio}\label{create-a-new-project-in-rstudio}}

\hypertarget{click-on-new-project-button-on-rstudio}{%
\subsection{\texorpdfstring{1.1 Click on \textbf{New Project} button on RStudio}{1.1 Click on New Project button on RStudio}}\label{click-on-new-project-button-on-rstudio}}

\includegraphics{images/new_project1.png}

\includegraphics{images/new_project2.png}

\hypertarget{create-a-new-directory}{%
\subsection{\texorpdfstring{1.2 Create a \textbf{New Directory}}{1.2 Create a New Directory}}\label{create-a-new-directory}}

\includegraphics{images/new_project3.png}

\hypertarget{select-new-project-as-project-type}{%
\subsection{\texorpdfstring{1.3 Select \textbf{New Project} as project type}{1.3 Select New Project as project type}}\label{select-new-project-as-project-type}}

\includegraphics{images/new_project4.png}

\hypertarget{specify-details-for-new-project}{%
\subsection{1.4 Specify details for new project}\label{specify-details-for-new-project}}

\includegraphics{images/new_project5.png}

1.4.1 Specify a project name. Best practices for naming a project are:

\begin{itemize}
\tightlist
\item
  Make sure that name is succinct (as short as possible while at the same time descriptive of the project);
\item
  Don't use spaces for your project name. If you need to separate words, use a \textbf{dash} or an \textbf{underscore};
\item
  Avoid using capital letters.
\end{itemize}

1.4.2 Specify a directory/location in your local machine where to place the directory of your new project

1.4.3 Decide whether to use git to version this project

Here you can decide whether you want to use \texttt{git} to version your project. Remember that using \texttt{git} doesn't mean you have to use GitHub. \texttt{git} is software installed in your local machine and it versions what you have on your local machine. You don't need \texttt{GitHub} or any other similar service to version your code with \texttt{git} in your local machine.

I would recommend that you tick this option for any new project you create so that you can version your work in your local machine even if you don't want or decide not to use \texttt{GitHub} or any other remote \texttt{git} service.

1.4.4 Do you want to open a new session

This is by default unticked and will open the new project within the existing RStudio session (if any). This means that if you have an existing RStudio session with another project that you are working on, that project will be closed and the new project you are creating will open in the existing RStudio session.

If you need your existing RStudio session and the project within it to remain open alongside the new project you are creating, tick this box/option.

1.4.4 Click on \textbf{Create New Project}

Once you click on \textbf{Create New Project}, you will now see the new project open in RStudio.

You will also see something like below witin the file explorer pane of RStudio.

\includegraphics{images/new_project6.png}

\hypertarget{structureorganise-your-new-project-appropriately}{%
\section{2. Structure/organise your new project appropriately}\label{structureorganise-your-new-project-appropriately}}

Project organisation is vital because:

\begin{itemize}
\tightlist
\item
  supports productivity because the different components of the project are placed in directories where they should be;
\item
  enables clarity in communicating project structure;
\item
  facilitates collaboration.
\end{itemize}

Organising an R project can be user- and project-dependent but there are generally accepted project organising structure that is common to most well-organised projects. Below is an example:

.
\textbar\_\_ my-project
\textbar-- data
\textbar-- output
\textbar-- figures
\textbar-- R
\textbar-- my-project.Rproj
\textbar-- analysis\_workflow.R
\textbar-- README.md

\hypertarget{start-coding}{%
\section{3. Start coding}\label{start-coding}}

This will include creating bespoke R functions (as required) and creating an Rscript for the step-by-step processes in your scientific workflow.

\hypertarget{next-steps}{%
\section{Next steps}\label{next-steps}}

The next steps will depend on whether you will use \texttt{git} and \texttt{GitHub} for versioning your project and whether or not you will work on your project as a solo scientiest or work and collaborate with other scientists.

\hypertarget{portable-reproducible}{%
\chapter{Creating portable and reproducible scientific workflows}\label{portable-reproducible}}

At this point, you would have written your own R code and R scripts and saved these within an R file (\texttt{.R}).

By now, you would have also appreciated how extensible R is through built-in packages and/or through functions that you have created yourself.

So far, in the examples that we have worked on, the operations and the problems have been quite straightforward. But from your own experience dealing with your own data, real world data is far from straightforward and far from simple. Complexity is almost always a given.

R's scripting capability and R's extensibility are its main characteristics that make R a good tool for creating robust scientific workflows particularly for complex data and research projects.

A typical scientific workflow would have the following steps:

\begin{center}\includegraphics[width=11.11in]{images/scientific-workflow} \end{center}

In general, an R script should reflect the different steps outlined above. Hence, an R script of a scientific workflow would tend to look like this:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Load libraries}


\DocumentationTok{\#\# Retrieve and read data}


\DocumentationTok{\#\# Process data}


\DocumentationTok{\#\# Analyse data}

\DocumentationTok{\#\#\# Descriptive analysis}

\DocumentationTok{\#\#\# Statistical tests}

\DocumentationTok{\#\#\# Model specifications}


\DocumentationTok{\#\# Outputs}

\DocumentationTok{\#\#\# Tabulation of results}

\DocumentationTok{\#\#\# Model outputs}

\DocumentationTok{\#\#\# Plots}


\DocumentationTok{\#\# Report}

\end{Highlighting}
\end{Shaded}

In this chapter, we will go through a step-by-step walkthrough of how to build a robust scientific workflow in R. A robust worklow is one that is \textbf{portable} i.e., not dependent on hardware and software and instead can be run on almost any machine with very minimal, if any, additional setup or configuration required, and one that is \textbf{reproducible} i.e., can be run over and over again without issues, providing the expected results with the same data or providing updated results with new and/or updated data.

\hypertarget{step-1-create-a-new-rstudio-project}{%
\section{Step 1: Create a new RStudio project}\label{step-1-create-a-new-rstudio-project}}

\begin{itemize}
\item
  Open RStudio
\item
  Click on the \texttt{File} option in the RStudio menu. In the dropdown menu, select \texttt{New\ Project}
\item
  In the menu window, select \texttt{New\ directory} option.
\item
  In the next menu window, select \texttt{New\ project} option.
\item
  In the next menu window, enter the following details:

  \begin{itemize}
  \item
    Name of the project - important to make the project name as short as possible but descriptive of the project you are creating; don't use spaces, instead use dash (or underscore) and avoid using capital letters;
  \item
    Select the directory in your computer in which you want to save the project in. Click on \texttt{Browse} to open your computers file manager and navigate to the directory you want to save your project in;
  \item
    Tick the selection box to make this project a git repository (whilst this is not necessary, this is highly recommended especially if you are collaborating with others);
  \item
    Tick the selection box to enable \texttt{renv} in this project (this is what mainly contribute to the portability of your project); and,
  \item
    Click on \texttt{Create\ project}
  \end{itemize}
\end{itemize}

\hypertarget{step-2-create-an-r-file-called-packages.r}{%
\section{\texorpdfstring{Step 2: Create an R file called \texttt{packages.R}}{Step 2: Create an R file called packages.R}}\label{step-2-create-an-r-file-called-packages.r}}

\begin{itemize}
\item
  Click on the \texttt{File} option in the RStudio menu. In the dropdown menu, select \texttt{New\ File} and then in the next dropdown menu, select \texttt{R\ script}.
\item
  A new tab will open in your text editor pane of RStudio (upper left pane) with the name \emph{Untitled1}. Save this file by clicking on the disk icon on the text editor menu or do a keyboard shortcut with \texttt{CTRL\ +\ s}. Give this empty R script the filename \texttt{packages.R}.
\item
  You should now see a file in the main directory/root directory of your project named \texttt{packages.R}
\item
  Add code in the \texttt{packages.R} file specifying the packages you will be using in this project. There will be standard packages that we will always use with this type of workflow. So a template/generic \texttt{packages.R} file will contain the following:
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\CommentTok{\#}
\CommentTok{\#\textquotesingle{}}
\CommentTok{\#\textquotesingle{} General packages needed for a targets workflow}
\CommentTok{\#\textquotesingle{}}
\CommentTok{\#}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}

\FunctionTok{library}\NormalTok{(targets)}
\FunctionTok{library}\NormalTok{(tarchetypes)}
\FunctionTok{library}\NormalTok{(here)}
\FunctionTok{library}\NormalTok{(rmarkdown)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(kableExtra)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(openxlsx)}
\FunctionTok{library}\NormalTok{(ggplot2)}


\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}
\CommentTok{\#}
\CommentTok{\#\textquotesingle{}}
\CommentTok{\#\textquotesingle{} Add other packages that will be used in the project below}
\CommentTok{\#\textquotesingle{}}
\CommentTok{\#}
\DocumentationTok{\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#\#}


\end{Highlighting}
\end{Shaded}

\hypertarget{step-3-create-placeholder-directories-for-different-components-of-workflow}{%
\section{Step 3: Create placeholder directories for different components of workflow}\label{step-3-create-placeholder-directories-for-different-components-of-workflow}}

\begin{itemize}
\item
  In the lower right pane of RStudio (the file manager pane), find the menu button labelled \texttt{Folder}.
\item
  Give this new folder the label of \texttt{R}. This filder will hold all bespoke functions that we will create to use for this project workflow;
\item
  Repeat these steps to create new folders with the following labels:

  \begin{itemize}
  \item
    \texttt{data} - This folder will hold any data that we retrieve as part of this workflow.
  \item
    \texttt{outputs} - This folder will hold all our workflow outputs such as plots/figures, tables (in Excel or CSV files), HTML and/or Word and/or PDF outputs
  \item
    \texttt{reports} - This folder will hold all our RMarkdown report (\texttt{.Rmd}) files
  \item
    \texttt{docs} - This folder will hold any of our deployed outputs such as HTML report, dashboard, etc.
  \end{itemize}
\end{itemize}

These are placeholder directories which we will populate as we work through the workflow for this project.

\hypertarget{step-4-create-the-target-script-file-_targets.r}{%
\section{\texorpdfstring{Step 4: Create the target script file (\texttt{\_targets.R})}{Step 4: Create the target script file (\_targets.R)}}\label{step-4-create-the-target-script-file-_targets.r}}

The next task is to create a \{targets\} script file (\texttt{\_targets.R}) which is the file that will define the workflow that we will be creating.

Create the file by:

\begin{itemize}
\item
  Clicking on File --\textgreater{} New File --\textgreater{} R Script in RStudio.
\item
  A new tab will show in your Source window on the top left quadrant of your RStudio screen. This tab will usually be called \texttt{Untitled1}.
\item
  Save this file first and change its name to \texttt{\_targets.R}. Make sure to save it in the current project directory.
\item
  You know that you were successful in doing this once you see a file called \texttt{\_targets.R} in the File system window in the lower right quadrant of your RStudio screen.
\end{itemize}

\hypertarget{step-5-edit-the-_targets.r-script-file}{%
\section{\texorpdfstring{Step 5: Edit the \texttt{\_targets.R} script file}{Step 5: Edit the \_targets.R script file}}\label{step-5-edit-the-_targets.r-script-file}}

Now, the next step is to edit your script file by adding sets of R code that does the following:

\begin{itemize}
\tightlist
\item
  Loads the packages required
\item
  Loads custom functions (if any)
\item
  Defines individual targets using \texttt{tar\_targets} function
\item
  Ends with a list of targets objects
\end{itemize}

A basic \texttt{\{targets\}} workflow will look like this:

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Load libraries {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\FunctionTok{library}\NormalTok{(targets)}



\DocumentationTok{\#\# Load custom functions {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\ControlFlowTok{for}\NormalTok{ (f }\ControlFlowTok{in} \FunctionTok{list.files}\NormalTok{(}\StringTok{"R"}\NormalTok{, }\AttributeTok{full.names =} \ConstantTok{TRUE}\NormalTok{)) }\FunctionTok{source}\NormalTok{ (f)}
\ControlFlowTok{for}\NormalTok{ (f }\ControlFlowTok{in} \FunctionTok{list.files}\NormalTok{(here}\SpecialCharTok{::}\FunctionTok{here}\NormalTok{(}\StringTok{"R"}\NormalTok{), }\AttributeTok{full.names =} \ConstantTok{TRUE}\NormalTok{)) }\FunctionTok{source}\NormalTok{ (f)}


\DocumentationTok{\#\# Create targets and list targets objects {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}


\end{Highlighting}
\end{Shaded}


  \bibliography{book.bib}

\end{document}
