<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Writing functions | University of Oxford International Health and Tropical Medicine</title>
  <meta name="description" content="A handbook for the MSc in International Health and Tropical Medicine Lecture Series on R and Reproducible Research" />
  <meta name="generator" content="bookdown 0.31 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Writing functions | University of Oxford International Health and Tropical Medicine" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="A handbook for the MSc in International Health and Tropical Medicine Lecture Series on R and Reproducible Research" />
  <meta name="github-repo" content="OxfordIHTM/ihtm-handbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Writing functions | University of Oxford International Health and Tropical Medicine" />
  
  <meta name="twitter:description" content="A handbook for the MSc in International Health and Tropical Medicine Lecture Series on R and Reproducible Research" />
  

<meta name="author" content="Proochista Ariana and Ernest Guevarra" />


<meta name="date" content="2023-01-11" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro-r.html"/>
<link rel="next" href="clone-repository.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Oxford IHTM Handbook</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Open Science and Reproducible Research Handbook</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="install-r.html"><a href="install-r.html"><i class="fa fa-check"></i><b>2</b> Installing R and RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="install-r.html"><a href="install-r.html#install-r-for-windows-machines"><i class="fa fa-check"></i><b>2.1</b> Install R for Windows machines</a></li>
<li class="chapter" data-level="2.2" data-path="install-r.html"><a href="install-r.html#install-rstudio"><i class="fa fa-check"></i><b>2.2</b> Install RStudio</a></li>
<li class="chapter" data-level="2.3" data-path="install-r.html"><a href="install-r.html#install-rtools"><i class="fa fa-check"></i><b>2.3</b> Install <code>Rtools</code></a></li>
<li class="chapter" data-level="2.4" data-path="install-r.html"><a href="install-r.html#install-git-for-windows"><i class="fa fa-check"></i><b>2.4</b> Install Git for Windows</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="intro-r.html"><a href="intro-r.html"><i class="fa fa-check"></i><b>3</b> Introduction to R and RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="intro-r.html"><a href="intro-r.html#what-r"><i class="fa fa-check"></i><b>3.1</b> What is R?</a></li>
<li class="chapter" data-level="3.2" data-path="intro-r.html"><a href="intro-r.html#why-r"><i class="fa fa-check"></i><b>3.2</b> Why use R?</a></li>
<li class="chapter" data-level="3.3" data-path="intro-r.html"><a href="intro-r.html#what-rstudio"><i class="fa fa-check"></i><b>3.3</b> What is RStudio</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="write-functions.html"><a href="write-functions.html"><i class="fa fa-check"></i><b>4</b> Writing functions</a></li>
<li class="chapter" data-level="5" data-path="clone-repository.html"><a href="clone-repository.html"><i class="fa fa-check"></i><b>5</b> Cloning a GitHub repository into your local computer using RStudio</a>
<ul>
<li class="chapter" data-level="5.1" data-path="clone-repository.html"><a href="clone-repository.html#copy-the-repository-url-of-the-repository-you-want-to-clone-from-github"><i class="fa fa-check"></i><b>5.1</b> Copy the repository URL of the repository you want to clone from GitHub</a></li>
<li class="chapter" data-level="5.2" data-path="clone-repository.html"><a href="clone-repository.html#go-to-rstudio-and-create-new-project"><i class="fa fa-check"></i><b>5.2</b> Go to RStudio and create new project</a></li>
<li class="chapter" data-level="5.3" data-path="clone-repository.html"><a href="clone-repository.html#choose-version-control"><i class="fa fa-check"></i><b>5.3</b> Choose Version Control</a></li>
<li class="chapter" data-level="5.4" data-path="clone-repository.html"><a href="clone-repository.html#select-git"><i class="fa fa-check"></i><b>5.4</b> Select Git</a></li>
<li class="chapter" data-level="5.5" data-path="clone-repository.html"><a href="clone-repository.html#setup-repository-settings"><i class="fa fa-check"></i><b>5.5</b> Setup repository settings</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="commit-and-push.html"><a href="commit-and-push.html"><i class="fa fa-check"></i><b>6</b> Committing your changes and pushing them to GitHub</a>
<ul>
<li class="chapter" data-level="6.1" data-path="commit-and-push.html"><a href="commit-and-push.html#click-on-commit-in-the-git-tab-on-rstudio"><i class="fa fa-check"></i><b>6.1</b> Click on <code>Commit</code> in the Git tab on RStudio</a></li>
<li class="chapter" data-level="6.2" data-path="commit-and-push.html"><a href="commit-and-push.html#getting-changes-saved-and-push-to-github"><i class="fa fa-check"></i><b>6.2</b> Getting changes saved and push to GitHub</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="portable-reproducible.html"><a href="portable-reproducible.html"><i class="fa fa-check"></i><b>7</b> Creating portable and reproducible scientific workflows</a>
<ul>
<li class="chapter" data-level="7.1" data-path="portable-reproducible.html"><a href="portable-reproducible.html#step-1-create-a-new-rstudio-project"><i class="fa fa-check"></i><b>7.1</b> Step 1: Create a new RStudio project</a></li>
<li class="chapter" data-level="7.2" data-path="portable-reproducible.html"><a href="portable-reproducible.html#step-2-create-an-r-file-called-packages.r"><i class="fa fa-check"></i><b>7.2</b> Step 2: Create an R file called <code>packages.R</code></a></li>
<li class="chapter" data-level="7.3" data-path="portable-reproducible.html"><a href="portable-reproducible.html#step-3-create-placeholder-directories-for-different-components-of-workflow"><i class="fa fa-check"></i><b>7.3</b> Step 3: Create placeholder directories for different components of workflow</a></li>
<li class="chapter" data-level="7.4" data-path="portable-reproducible.html"><a href="portable-reproducible.html#step-4-create-the-target-script-file-_targets.r"><i class="fa fa-check"></i><b>7.4</b> Step 4: Create the target script file (<code>_targets.R</code>)</a></li>
<li class="chapter" data-level="7.5" data-path="portable-reproducible.html"><a href="portable-reproducible.html#step-5-edit-the-_targets.r-script-file"><i class="fa fa-check"></i><b>7.5</b> Step 5: Edit the <code>_targets.R</code> script file</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="" target="blank">@ University of Oxford International Health and Tropical Medicine 2023</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">University of Oxford International Health and Tropical Medicine</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="write-functions" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Writing functions<a href="write-functions.html#write-functions" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>For this topic, we will use data on weight and height to calculate body mass index. As a refresher, body mass index is calculated as follows:</p>
<p><span class="math display">\[ \text{Body mass index} ~=~ \frac{weight ~ (kgs)}{height ~ (m) ^ 2} \]</span>
For this topic on writing functions in R, we will use BMI as an example to explore and demonstrate how we can create our own functions in R.</p>
<p>Let’s say for example that you have been doing a research on children aged 11 years and older in 3 schools and you have collected the following data:</p>
<p><strong>School 1516</strong></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="write-functions.html#cb2-1" aria-hidden="true" tabindex="-1"></a>school1516</span></code></pre></div>
<pre><code>##     school sex ageMonths weight height
## 427   1516   1       138   24.5  126.0
## 428   1516   1       150   28.3  136.3
## 429   1516   1       162   32.2  143.5
## 430   1516   1       162   32.7  143.5
## 431   1516   1       150   28.6  137.0
## 432   1516   2       138   26.5  134.0
## 433   1516   1       150   29.9  139.2
## 434   1516   1       150   30.0  139.5
## 435   1516   1       162   34.0  148.0
## 436   1516   1       138   25.4  135.7
## 437   1516   1       150   32.3  143.0
## 438   1516   2       174   38.3  153.5
## 439   1516   2       162   41.6  151.0
## 440   1516   1       150   30.7  145.0
## 441   1516   2       186   46.8  155.2
## 442   1516   1       186   46.6  163.4
## 443   1516   1       150   33.5  145.5
## 444   1516   1       186   47.0  164.0
## 445   1516   1       174   41.1  159.5
## 446   1516   2       162   39.1  152.2
## 447   1516   2       174   40.9  155.5
## 448   1516   2       162   39.7  153.0
## 449   1516   2       162   40.9  153.2
## 450   1516   1       150   34.2  147.5
## 451   1516   2       150   41.8  149.4
## 452   1516   1       138   28.0  141.5
## 453   1516   1       138   30.0  142.0
## 454   1516   1       138   33.1  142.0
## 455   1516   1       186   46.1  167.5
## 456   1516   1       150   36.2  149.0
## 457   1516   2       162   47.4  156.0
## 458   1516   1       150   30.3  150.2
## 459   1516   2       150   36.4  152.1
## 460   1516   2       150   36.4  155.0
## 461   1516   2       150   44.1  155.0
## 462   1516   2       162   42.3  160.1
## 463   1516   2       179   50.4  163.5
## 464   1516   1       150   37.6  155.0
## 465   1516   2       138   36.0  154.5
## 466   1516   2       138   46.1  156.0</code></pre>
<p><strong>School 1522</strong></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="write-functions.html#cb4-1" aria-hidden="true" tabindex="-1"></a>school1522</span></code></pre></div>
<pre><code>##     school sex ageMonths weight height
## 646   1522   1       203   30.6  140.5
## 647   1522   1       174   30.8  140.0
## 648   1522   1       162   29.3  136.3
## 649   1522   1       150   24.0  132.0
## 650   1522   1       150   28.1  132.1
## 651   1522   2       150   27.2  134.9
## 652   1522   1       162   34.2  139.2
## 653   1522   1       150   25.5  134.2
## 654   1522   1       138   24.6  129.0
## 655   1522   1       174   36.4  147.5
## 656   1522   1       150   28.7  137.5
## 657   1522   1       186   45.8  155.6
## 658   1522   1       174   36.3  151.6
## 659   1522   1       150   31.0  139.5
## 660   1522   1       138   29.0  134.3
## 661   1522   1       179   38.3  155.5
## 662   1522   2       138   31.3  138.4
## 663   1522   1       162   36.5  148.8
## 664   1522   1       155   36.8  145.2
## 665   1522   1       138   28.3  136.8
## 666   1522   1       138   26.8  137.3
## 667   1522   2       138   32.6  141.4
## 668   1522   2       138   31.9  143.0
## 669   1522   1       174   42.6  160.7
## 670   1522   2       198   57.8  158.0
## 671   1522   2       162   43.9  153.5
## 672   1522   2       150   35.1  150.6
## 673   1522   2       186   52.6  159.6
## 674   1522   2       150   45.1  152.8
## 675   1522   2       138   34.6  147.2
## 676   1522   2       150   45.3  153.1
## 677   1522   1       186   51.8  170.2
## 678   1522   2       150   57.1  154.2
## 679   1522   2       138   33.5  149.2
## 680   1522   1       150   36.3  154.1
## 681   1522   1       174   44.0  169.1
## 682   1522   2       150   44.5  158.3
## 683   1522   2       150   51.5  159.1
## 684   1522   2       138   47.4  157.8
## 685   1522   2       138   36.8  158.5
## 686   1522   2       138   52.0  161.0</code></pre>
<p><strong>School 1525</strong></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="write-functions.html#cb6-1" aria-hidden="true" tabindex="-1"></a>school1525</span></code></pre></div>
<pre><code>##     school sex ageMonths weight height
## 752   1525   1       186   26.2    137
## 753   1525   1       186   32.7    138
## 754   1525   1       150   25.9    130
## 755   1525   1       162   30.4    137
## 756   1525   2       138   24.4    129
## 757   1525   2       138   23.8    130
## 758   1525   1       150   26.1    133
## 759   1525   1       150   26.4    135
## 760   1525   1       174   35.1    148
## 761   1525   1       162   28.7    142
## 762   1525   1       150   28.0    136
## 763   1525   1       174   34.0    149
## 764   1525   1       186   40.6    155
## 765   1525   2       150   35.8    142
## 766   1525   1       150   35.4    140
## 767   1525   2       138   27.8    137
## 768   1525   2       138   28.2    137
## 769   1525   2       138   29.7    139
## 770   1525   2       138   30.9    139
## 771   1525   1       138   28.2    137
## 772   1525   2       138   26.2    140
## 773   1525   2       138   26.6    140
## 774   1525   1       138   27.2    138
## 775   1525   2       138   27.0    141
## 776   1525   1       150   31.3    145
## 777   1525   2       162   33.9    152
## 778   1525   2       162   42.0    153
## 779   1525   2       185   38.3    157
## 780   1525   2       138   31.0    145
## 781   1525   2       138   32.3    145
## 782   1525   1       139   35.1    144
## 783   1525   2       150   36.4    152
## 784   1525   2       138   32.7    147
## 785   1525   1       174   44.9    166
## 786   1525   2       138   32.2    148
## 787   1525   2       138   36.4    148
## 788   1525   1       138   31.4    146
## 789   1525   2       138   45.0    149
## 790   1525   2       162   49.4    160
## 791   1525   2       138   34.3    150
## 792   1525   1       138   30.0    148
## 793   1525   2       150   37.0    156
## 794   1525   2       162   52.2    165
## 795   1525   2       138   42.9    158</code></pre>
<p>In this dataset, the units of the height measurement is in centimetres.</p>
<p>Using what we have learned earlier on calculating BMI using R, I can perform the following R commands to get the BMI for each child in each of the schools:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="write-functions.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb8-2"><a href="write-functions.html#cb8-2" aria-hidden="true" tabindex="-1"></a>school1516<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb8-3"><a href="write-functions.html#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="write-functions.html#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb8-5"><a href="write-functions.html#cb8-5" aria-hidden="true" tabindex="-1"></a>school1522<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb8-6"><a href="write-functions.html#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="write-functions.html#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb8-8"><a href="write-functions.html#cb8-8" aria-hidden="true" tabindex="-1"></a>school1525<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<p>Because the commands are repetitive, I can easily copy and paste my initial line of code to calculate BMI for children in school 1516 and then just change the object names accordingly to calculate the BMI for children in the two other schools.</p>
<p>When I run these lines of code, I get the following results:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="write-functions.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb9-2"><a href="write-functions.html#cb9-2" aria-hidden="true" tabindex="-1"></a>school1516<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 15.43210 15.23333 15.63695 15.87976 15.23789 14.75830 15.43095 15.41604 15.52228 13.79349 15.79539 16.25481 18.24481
## [14] 14.60166 19.42954 17.45347 15.82409 17.47472 16.15550 16.87903 16.91463 16.95929 17.42632 15.71962 18.72730 13.98444
## [27] 14.87800 16.41539 16.43128 16.30557 19.47732 13.43083 15.73414 15.15088 18.35588 16.50280 18.85363 15.65036 15.08153
## [40] 18.94313</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="write-functions.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb11-2"><a href="write-functions.html#cb11-2" aria-hidden="true" tabindex="-1"></a>school1522<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## Warning in school1522$weight/(school1516$height/100)^2: longer object length is not a multiple of shorter object length</code></pre>
<pre><code>##  [1] 19.27438 16.57903 14.22865 11.65487 14.97150 15.14814 17.65012 13.10363 11.23083 19.76704 14.03492 19.43787 15.92035
## [14] 14.74435 12.03967 14.34481 14.78490 13.57079 14.46527 12.21679 11.08343 13.92627 13.59168 19.58058 25.89564 21.92561
## [27] 17.40726 26.08609 16.07485 15.58488 18.61440 22.96095 24.68185 13.94381 15.10926 17.16604 16.64656 21.43600 19.85735
## [40] 15.12163 32.75384</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="write-functions.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb14-2"><a href="write-functions.html#cb14-2" aria-hidden="true" tabindex="-1"></a>school1525<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>## Warning in school1525$weight/(school1516$height/100)^2: longer object length is not a multiple of shorter object length</code></pre>
<pre><code>##  [1] 16.50290 17.60176 12.57755 14.76284 13.00016 13.25462 13.46983 13.56612 16.02447 15.58555 13.69260 14.42986 17.80624
## [14] 17.02735 14.69670 10.41216 13.32058 11.04253 12.14611 12.17362 10.83529 11.36315 11.58914 12.41023 14.02307 16.93116
## [27] 20.82920 18.99425 11.04923 14.54889 14.42308 16.13472 14.13479 18.68887 13.40271 14.20099 11.74611 18.73049 20.69522
## [40] 14.09435 18.89645 19.91636 25.34934 20.83308</code></pre>
<p>The calculation for the BMI of children in school 1516 seems to have completed without issues and a vector of BMI results have been produced. However, for school 1522 and school 1525, there is a warning saying:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="write-functions.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Warning in school1522$weight/(school1516$height)^2: longer object length is not a multiple</span></span>
<span id="cb17-2"><a href="write-functions.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="do">## of shorter object length</span></span></code></pre></div>
<p>Although a result has been provided, the warning gives me an indication that someting is not quite right with my calculation and when I inspect further, I notice that in my formula for school 1522 and for school 1525, my denominator is still using data for school 1516 and this is most likely what is causing the warning message.</p>
<p>So, to correct this I go back to my lines of code and edit the denominators for school 1522 and school 1525 as follows:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="write-functions.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb18-2"><a href="write-functions.html#cb18-2" aria-hidden="true" tabindex="-1"></a>school1516<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb18-3"><a href="write-functions.html#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="write-functions.html#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb18-5"><a href="write-functions.html#cb18-5" aria-hidden="true" tabindex="-1"></a>school1522<span class="sc">$</span>weight <span class="sc">/</span> (school1522<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb18-6"><a href="write-functions.html#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="write-functions.html#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb18-8"><a href="write-functions.html#cb18-8" aria-hidden="true" tabindex="-1"></a>school1525<span class="sc">$</span>weight <span class="sc">/</span> (school1525<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<p>which gives me:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="write-functions.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb19-2"><a href="write-functions.html#cb19-2" aria-hidden="true" tabindex="-1"></a>school1516<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 15.43210 15.23333 15.63695 15.87976 15.23789 14.75830 15.43095 15.41604 15.52228 13.79349 15.79539 16.25481 18.24481
## [14] 14.60166 19.42954 17.45347 15.82409 17.47472 16.15550 16.87903 16.91463 16.95929 17.42632 15.71962 18.72730 13.98444
## [27] 14.87800 16.41539 16.43128 16.30557 19.47732 13.43083 15.73414 15.15088 18.35588 16.50280 18.85363 15.65036 15.08153
## [40] 18.94313</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="write-functions.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb21-2"><a href="write-functions.html#cb21-2" aria-hidden="true" tabindex="-1"></a>school1522<span class="sc">$</span>weight <span class="sc">/</span> (school1522<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 15.50132 15.71429 15.77161 13.77410 16.10277 14.94669 17.65012 14.15908 14.78277 16.73082 15.18017 18.91674 15.79459
## [14] 15.92991 16.07852 15.83937 16.34076 16.48493 17.45479 15.12217 14.21653 16.30492 15.59978 16.49597 23.15334 18.63150
## [27] 15.47594 20.65000 19.31656 15.96837 19.32626 17.88178 24.01416 15.04898 15.28626 15.38741 17.75817 20.34543 19.03550
## [40] 14.64837 20.06095</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="write-functions.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb23-2"><a href="write-functions.html#cb23-2" aria-hidden="true" tabindex="-1"></a>school1525<span class="sc">$</span>weight <span class="sc">/</span> (school1525<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span></code></pre></div>
<pre><code>##  [1] 13.95919 17.17076 15.32544 16.19692 14.66258 14.08284 14.75493 14.48560 16.02447 14.23329 15.13841 15.31463 16.89906
## [14] 17.75441 18.06122 14.81166 15.02477 15.37188 15.99296 15.02477 13.36735 13.57143 14.28271 13.58081 14.88704 14.67278
## [27] 17.94182 15.53816 14.74435 15.36266 16.92708 15.75485 15.13258 16.29409 14.70051 16.61797 14.73072 20.26936 19.29687
## [40] 15.24444 13.69613 15.20381 19.17355 17.18475</code></pre>
<p>I now do not get the warning message and the expected length of BMI values for each school has now been produced.</p>
<p>From this short example above, we realise how tedious a task it is to type in the code above every time we need to calculate BMI. Also, it becomes even challenging to debug issues with the code because we have to review and edit (as needed) each iteration of the calculation to see where it may have gone wrong (especially when doing a cut and paste approach).</p>
<p>It would be better (and easier) to have a function that calculates and displays the BMI values automatically. Fortunately, <code>R</code> allows us to do just that.</p>
<p>The <code>function()</code> function allows us to create new functions in <code>R</code> with the following generic syntax:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="write-functions.html#cb25-1" aria-hidden="true" tabindex="-1"></a>function_name <span class="ot">&lt;-</span> <span class="cf">function</span>(argument1, argument2, ...) {</span>
<span id="cb25-2"><a href="write-functions.html#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Your code here</span></span>
<span id="cb25-3"><a href="write-functions.html#cb25-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Using this template/generic syntax, we apply it to create a function called <code>calculate_bmi</code> as follows:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="write-functions.html#cb26-1" aria-hidden="true" tabindex="-1"></a>calculate_bmi <span class="ot">&lt;-</span> <span class="cf">function</span>(weight, height) {</span>
<span id="cb26-2"><a href="write-functions.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  weight <span class="sc">/</span> height <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb26-3"><a href="write-functions.html#cb26-3" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>We now have a function for calculating and outputing BMI values.</p>
<p>Let us now test it with our 3 sets of data:</p>
<p><strong>School 1516</strong></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="write-functions.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calculate_bmi</span>(</span>
<span id="cb27-2"><a href="write-functions.html#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight =</span> school1516<span class="sc">$</span>weight,</span>
<span id="cb27-3"><a href="write-functions.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span></span>
<span id="cb27-4"><a href="write-functions.html#cb27-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##  [1] 15.43210 15.23333 15.63695 15.87976 15.23789 14.75830 15.43095 15.41604 15.52228 13.79349 15.79539 16.25481 18.24481
## [14] 14.60166 19.42954 17.45347 15.82409 17.47472 16.15550 16.87903 16.91463 16.95929 17.42632 15.71962 18.72730 13.98444
## [27] 14.87800 16.41539 16.43128 16.30557 19.47732 13.43083 15.73414 15.15088 18.35588 16.50280 18.85363 15.65036 15.08153
## [40] 18.94313</code></pre>
<p><strong>School 1522</strong></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="write-functions.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calculate_bmi</span>(</span>
<span id="cb29-2"><a href="write-functions.html#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight =</span> school1522<span class="sc">$</span>weight,</span>
<span id="cb29-3"><a href="write-functions.html#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> school1522<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span></span>
<span id="cb29-4"><a href="write-functions.html#cb29-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##  [1] 15.50132 15.71429 15.77161 13.77410 16.10277 14.94669 17.65012 14.15908 14.78277 16.73082 15.18017 18.91674 15.79459
## [14] 15.92991 16.07852 15.83937 16.34076 16.48493 17.45479 15.12217 14.21653 16.30492 15.59978 16.49597 23.15334 18.63150
## [27] 15.47594 20.65000 19.31656 15.96837 19.32626 17.88178 24.01416 15.04898 15.28626 15.38741 17.75817 20.34543 19.03550
## [40] 14.64837 20.06095</code></pre>
<p><strong>School 1525</strong></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="write-functions.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calculate_bmi</span>(</span>
<span id="cb31-2"><a href="write-functions.html#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight =</span> school1525<span class="sc">$</span>weight,</span>
<span id="cb31-3"><a href="write-functions.html#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> school1525<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span></span>
<span id="cb31-4"><a href="write-functions.html#cb31-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>##  [1] 13.95919 17.17076 15.32544 16.19692 14.66258 14.08284 14.75493 14.48560 16.02447 14.23329 15.13841 15.31463 16.89906
## [14] 17.75441 18.06122 14.81166 15.02477 15.37188 15.99296 15.02477 13.36735 13.57143 14.28271 13.58081 14.88704 14.67278
## [27] 17.94182 15.53816 14.74435 15.36266 16.92708 15.75485 15.13258 16.29409 14.70051 16.61797 14.73072 20.26936 19.29687
## [40] 15.24444 13.69613 15.20381 19.17355 17.18475</code></pre>
<p>In our example here, the <code>calculate_bmi()</code> function helped a little bit in making the code to calculate BMI for each student in each school more efficient. But the efficiency that functions provide become more evident when you need to make more complex operations. For example, what if you need to get the mean BMI for students in each school? Without a function, we will have to do the following script for each school:</p>
<p><strong>School 1516</strong></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="write-functions.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1516</span></span>
<span id="cb33-2"><a href="write-functions.html#cb33-2" aria-hidden="true" tabindex="-1"></a>bmi_school1516 <span class="ot">&lt;-</span> school1516<span class="sc">$</span>weight <span class="sc">/</span> (school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb33-3"><a href="write-functions.html#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="write-functions.html#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Get the mean BMI for children in school 1516</span></span>
<span id="cb33-5"><a href="write-functions.html#cb33-5" aria-hidden="true" tabindex="-1"></a>mean_bmi_school1516 <span class="ot">&lt;-</span> <span class="fu">mean</span>(bmi_school1516)</span>
<span id="cb33-6"><a href="write-functions.html#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="write-functions.html#cb33-7" aria-hidden="true" tabindex="-1"></a>mean_bmi_school1516</span></code></pre></div>
<pre><code>## [1] 16.28491</code></pre>
<p><strong>School 1522</strong></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="write-functions.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1522</span></span>
<span id="cb35-2"><a href="write-functions.html#cb35-2" aria-hidden="true" tabindex="-1"></a>bmi_school1522 <span class="ot">&lt;-</span> school1522<span class="sc">$</span>weight <span class="sc">/</span> (school1522<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span>) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb35-3"><a href="write-functions.html#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="write-functions.html#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Get the mean BMI for children in school 1522</span></span>
<span id="cb35-5"><a href="write-functions.html#cb35-5" aria-hidden="true" tabindex="-1"></a>mean_bmi_school1522 <span class="ot">&lt;-</span> <span class="fu">mean</span>(bmi_school1522)</span>
<span id="cb35-6"><a href="write-functions.html#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="write-functions.html#cb35-7" aria-hidden="true" tabindex="-1"></a>mean_bmi_school1522</span></code></pre></div>
<pre><code>## [1] 16.89955</code></pre>
<p><strong>School 1525</strong></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="write-functions.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate BMI for children in school 1525</span></span>
<span id="cb37-2"><a href="write-functions.html#cb37-2" aria-hidden="true" tabindex="-1"></a>bmi_school1525 <span class="ot">&lt;-</span> school1525<span class="sc">$</span>weight <span class="sc">/</span> (school1525<span class="sc">$</span>height) <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb37-3"><a href="write-functions.html#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="write-functions.html#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Get the mean BMI for children in school 1525</span></span>
<span id="cb37-5"><a href="write-functions.html#cb37-5" aria-hidden="true" tabindex="-1"></a>mean_bmi_school1525 <span class="ot">&lt;-</span> <span class="fu">mean</span>(bmi_school1525)</span>
<span id="cb37-6"><a href="write-functions.html#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="write-functions.html#cb37-7" aria-hidden="true" tabindex="-1"></a>mean_bmi_school1525</span></code></pre></div>
<pre><code>## [1] 0.001564695</code></pre>
<p>As the operations/calculations we want to perform become more complex, the copy and paste method becomes more and more tedious. With the function approach, we can use the following:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="write-functions.html#cb39-1" aria-hidden="true" tabindex="-1"></a>calculate_mean_bmi <span class="ot">&lt;-</span> <span class="cf">function</span>(weight, height) {</span>
<span id="cb39-2"><a href="write-functions.html#cb39-2" aria-hidden="true" tabindex="-1"></a>  bmi <span class="ot">&lt;-</span> weight <span class="sc">/</span> height <span class="sc">^</span> <span class="dv">2</span></span>
<span id="cb39-3"><a href="write-functions.html#cb39-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-4"><a href="write-functions.html#cb39-4" aria-hidden="true" tabindex="-1"></a>  mean_bmi <span class="ot">&lt;-</span> <span class="fu">mean</span>(bmi)</span>
<span id="cb39-5"><a href="write-functions.html#cb39-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb39-6"><a href="write-functions.html#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(mean_bmi)</span>
<span id="cb39-7"><a href="write-functions.html#cb39-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Applying the function to the datasets, we get:</p>
<p><strong>School 1516</strong></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="write-functions.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calculate_mean_bmi</span>(</span>
<span id="cb40-2"><a href="write-functions.html#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight =</span> school1516<span class="sc">$</span>weight,</span>
<span id="cb40-3"><a href="write-functions.html#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> school1516<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span></span>
<span id="cb40-4"><a href="write-functions.html#cb40-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## [1] 16.28491</code></pre>
<p><strong>School 1522</strong></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="write-functions.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calculate_mean_bmi</span>(</span>
<span id="cb42-2"><a href="write-functions.html#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight =</span> school1522<span class="sc">$</span>weight,</span>
<span id="cb42-3"><a href="write-functions.html#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> school1522<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span></span>
<span id="cb42-4"><a href="write-functions.html#cb42-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## [1] 16.89955</code></pre>
<p><strong>School 1525</strong></p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="write-functions.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calculate_mean_bmi</span>(</span>
<span id="cb44-2"><a href="write-functions.html#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">weight =</span> school1525<span class="sc">$</span>weight,</span>
<span id="cb44-3"><a href="write-functions.html#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">height =</span> school1525<span class="sc">$</span>height <span class="sc">/</span> <span class="dv">100</span></span>
<span id="cb44-4"><a href="write-functions.html#cb44-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## [1] 15.64695</code></pre>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro-r.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="clone-repository.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ihtm-handbook.pdf", "ihtm-handbook.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
